# Generated by Django 3.2.2 on 2021-05-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, null=True)),
                ('chain', models.CharField(max_length=256)),
                ('addr', models.CharField(max_length=256, null=True)),
                ('city_name', models.CharField(max_length=128)),
                ('state_name', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='tax applied to purchases, in %')),
            ],
            options={
                'ordering': ['chain', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('card', models.CharField(max_length=4, null=True, unique=True, verbose_name='optional, last 4 digits of card #')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='purchase date')),
                ('time', models.TimeField(null=True, verbose_name='purchase time')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total balance due, including tax and discounts')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='balance due before tsx and discounts')),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='balance deductions for coupons, rewards programs, etc.')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='tax charges incurred')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipts.paymentmethod', verbose_name='payment method')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receipts.marketlocation', verbose_name='market/store location')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
