# Generated by Django 3.2.2 on 2021-05-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketlocation',
            name='addr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='marketlocation',
            name='chain',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='marketlocation',
            name='city_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='marketlocation',
            name='label',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketlocation',
            name='state_name',
            field=models.CharField(max_length=64),
        ),
    ]
