# Generated by Django 3.2.2 on 2021-05-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_grocerydepartment_groceryitem_groceryitemsize_groceryitemvariety_receiptlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='receipts.groceryitembrand'),
        ),
    ]
