# Generated by Django 3.2.2 on 2021-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_auto_20210513_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitemsize',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='quantitative measure of size (if applicable)'),
        ),
        migrations.AlterField(
            model_name='groceryitemsize',
            name='desc',
            field=models.CharField(max_length=32, verbose_name='description of size (taken as unit of measure if quantity is given)'),
        ),
    ]
